import { registry } from "./registry.js";
import { command as help } from "./help.js";
import { command as status } from "./status.js";
import { command as model } from "./model.js";
import { command as sessions } from "./sessions.js";
import { command as context } from "./context.js";
import { command as memory } from "./memory.js";
import { command as rules } from "./rules.js";
import { command as learning } from "./learning.js";
import { command as review } from "./review.js";
import { command as run } from "./run.js";
import { command as commit } from "./commit.js";
import { command as diff } from "./diff.js";
import { command as clear } from "./clear.js";
import { command as summary } from "./summary.js";
import { command as cost } from "./cost.js";
import { command as doctor } from "./doctor.js";
import { command as compact } from "./compact.js";
import { command as vim } from "./vim.js";
import { command as proactive } from "./proactive.js";
import { command as permissions } from "./permissions.js";
import { command as skill } from "./skill.js";
import { command as tasks } from "./tasks.js";
import { command as hooks } from "./hooks.js";
import { command as route } from "./route.js";
import { command as mcp } from "./mcp.js";
import { command as plugins } from "./plugins.js";
import { command as copy } from "./copy.js";
import { command as exportCmd } from "./export.js";
import { command as rename } from "./rename.js";
import { command as fork } from "./fork.js";
import { command as rewind } from "./rewind.js";
import { command as agents } from "./agents.js";
import { command as todos } from "./todos.js";
import { command as usage } from "./usage.js";
import { command as upgrade } from "./upgrade.js";
import { command as image } from "./image.js";
import { command as goal } from "./goal.js";

export function registerAllCommands(): void {
  registry.register(help);
  registry.register(status);
  registry.register(model);
  registry.register(sessions);
  registry.register(context);
  registry.register(memory);
  registry.register(rules);
  registry.register(learning);
  registry.register(review);
  registry.register(run);
  registry.register(commit);
  registry.register(diff);
  registry.register(clear);
  registry.register(summary);
  registry.register(cost);
  registry.register(doctor);
  registry.register(compact);
  registry.register(vim);
  registry.register(proactive);
  registry.register(permissions);
  registry.register(skill);
  registry.register(tasks);
  registry.register(hooks);
  registry.register(route);
  registry.register(mcp);
  registry.register(plugins);
  registry.register(copy);
  registry.register(exportCmd);
  registry.register(rename);
  registry.register(fork);
  registry.register(rewind);
  registry.register(agents);
  registry.register(todos);
  registry.register(usage);
  registry.register(upgrade);
  registry.register(image);
  registry.register(goal);
}
